In [5]:
import numpy as np
import pandas as pd

In [6]:
# import csv file
df = pd.read_csv("./cricketData.csv")
df

,Player,Span,Mat,Inns,NO,Runs,HS,*Ave*,BF,SR,100,50,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,*99.94*,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,*61.87*,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,*60.97*,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,*60.83*,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,*60.73*,6558+,34.59,16,23,2,202+,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,SPD Smith (AUS),2010-2025,115*,205,25,10140,239,*56.33*,18922,53.58,35,41,11,1106,60
76,JH Kallis (ICC/SA),1995-2013,166,280,40,13289,224,*55.37*,28903,45.97,45,58,16,1488,97
77,GE Tyldesley (ENG),1921-1929,14,20,2,990,122,*55.00*,178+,29.21,3,6,2,37+,2
78,KS Williamson (NZ),2010-2024,105,186,17,9276,251,*54.88*,17913,51.78,33,37,11,1031,27
79,CA Davis (WI),1968-1973,15,29,5,1301,183,*54.20*,665+,35.48,4,4,1,65+,1

In [7]:
# rename the columns to make more sense

In [8]:
df.rename(columns={"Mat":"MatchesPlayed", "Inns":"Innings","NO":"NotOuts",
                   "HS":"HighestScore", "*Ave*":"AverageScore", "BF":"BallsFaced",
                   "SR":"StrikeRate", "100":"Centuries", "50":"HalfCenturies"}, inplace=True)

In [9]:
df.head()

,Player,Span,MatchesPlayed,Innings,NotOuts,Runs,HighestScore,AverageScore,BallsFaced,StrikeRate,Centuries,HalfCenturies,0,4s,6s
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,*99.94*,9800+,58.60,29,13,7,626+,6
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,*61.87*,2667,55.68,5,4,2,186,5
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,*60.97*,1707+,54.48,7,11,1,246+,11
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,*60.83*,416+,56.00,10,5,2,104+,1
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,*60.73*,6558+,34.59,16,23,2,202+,6

In [10]:
df.isnull().any()

Player           False
Span             False
MatchesPlayed    False
Innings          False
NotOuts          False
Runs             False
HighestScore     False
AverageScore     False
BallsFaced       False
StrikeRate       False
Centuries        False
HalfCenturies    False
0                False
4s               False
6s               False
dtype: bool

In [11]:
df.loc[df["BallsFaced"]=="-", "BallsFaced"] = np.nan # there were values who had '-' for null

In [12]:
df = df.replace(0, np.nan) # making the 0's in the dataframe as null

In [13]:
# Balls faced column has a string value, thus put 0 in place of null values

In [14]:
df["BallsFaced"] = df["BallsFaced"].fillna(0)

In [15]:
df["BallsFaced"].isna().sum()

np.int64(0)

In [16]:
# remove null values from "StrikeRate" columns

In [17]:
df["StrikeRate"] = df["StrikeRate"].interpolate()

In [18]:
df["StrikeRate"].isna().sum()

np.int64(0)

In [19]:
df.isnull().any() # null values are handled successfully

Player           False
Span             False
MatchesPlayed    False
Innings          False
NotOuts          False
Runs             False
HighestScore     False
AverageScore     False
BallsFaced       False
StrikeRate       False
Centuries        False
HalfCenturies    False
0                False
4s               False
6s               False
dtype: bool

In [20]:
# remove duplicate values

In [21]:
#search if duplicate values exists or not
df.duplicated().sum()

np.int64(19)

In [22]:
# drop the duplicate values
df = df.drop_duplicates()

In [23]:
df.duplicated().sum() # would return zero now!

np.int64(0)

In [24]:
# Split up Span Date into Start-Date and End-Date

In [25]:
df["Start-Date"] = df.loc[:, "Span"].str.split("-").str[0]
df["End-Date"] = df.loc[:, "Span"].str.split("-").str[1]

In [26]:
df

,Player,Span,MatchesPlayed,Innings,NotOuts,Runs,HighestScore,AverageScore,BallsFaced,StrikeRate,Centuries,HalfCenturies,0,4s,6s,Start-Date,End-Date
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,*99.94*,9800+,58.60,29,13,7,626+,6,1928,1948
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,*61.87*,2667,55.68,5,4,2,186,5,2015,2016
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,*60.97*,1707+,54.48,7,11,1,246+,11,1963,1970
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,*60.83*,416+,56.00,10,5,2,104+,1,1930,1954
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,*60.73*,6558+,34.59,16,23,2,202+,6,1924,1935
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,KD Walters (AUS),1965-1981,74,125,14,5357,250,*48.26*,8662+,49.16,15,33,4,525+,23,1965,1981
57,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,*48.25*,15525,59.67,27,38,11,1165,24,2002,2014
58,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,*48.22*,3118+,44.77,7,6,1,119+,0,1924,1934
59,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,*48.21*,3217+,60.02,6,13,4,241+,5+,1930,1938
60,DR Jardine (ENG),1928-1934,22,33,6,1296,127,*48.00*,2110+,25.59,1,10,2,53+,0,1928,1934

In [27]:
# add new column -> Career Length

In [28]:
df["Career-Length"] = np.int64(df["End-Date"]) - np.int64(df["Start-Date"])

In [29]:
df

,Player,Span,MatchesPlayed,Innings,NotOuts,Runs,HighestScore,AverageScore,BallsFaced,StrikeRate,Centuries,HalfCenturies,0,4s,6s,Start-Date,End-Date,Career-Length
0,DG Bradman (AUS),1928-1948,52,80,10,6996,334,*99.94*,9800+,58.60,29,13,7,626+,6,1928,1948,20
1,AC Voges (AUS),2015-2016,20,31,7,1485,269*,*61.87*,2667,55.68,5,4,2,186,5,2015,2016,1
2,RG Pollock (SA),1963-1970,23,41,4,2256,274,*60.97*,1707+,54.48,7,11,1,246+,11,1963,1970,7
3,GA Headley (WI),1930-1954,22,40,4,2190,270*,*60.83*,416+,56.00,10,5,2,104+,1,1930,1954,24
4,H Sutcliffe (ENG),1924-1935,54,84,9,4555,194,*60.73*,6558+,34.59,16,23,2,202+,6,1924,1935,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,KD Walters (AUS),1965-1981,74,125,14,5357,250,*48.26*,8662+,49.16,15,33,4,525+,23,1965,1981,16
57,GC Smith (ICC/SA),2002-2014,117,205,13,9265,277,*48.25*,15525,59.67,27,38,11,1165,24,2002,2014,12
58,WH Ponsford (AUS),1924-1934,29,48,4,2122,266,*48.22*,3118+,44.77,7,6,1,119+,0,1924,1934,10
59,SJ McCabe (AUS),1930-1938,39,62,5,2748,232,*48.21*,3217+,60.02,6,13,4,241+,5+,1930,1938,8
60,DR Jardine (ENG),1928-1934,22,33,6,1296,127,*48.00*,2110+,25.59,1,10,2,53+,0,1928,1934,6

In [30]:
#Drop Span Columns

In [31]:
df = df.drop(columns=['Span'])

In [32]:
df

,Player,MatchesPlayed,Innings,NotOuts,Runs,HighestScore,AverageScore,BallsFaced,StrikeRate,Centuries,HalfCenturies,0,4s,6s,Start-Date,End-Date,Career-Length
0,DG Bradman (AUS),52,80,10,6996,334,*99.94*,9800+,58.60,29,13,7,626+,6,1928,1948,20
1,AC Voges (AUS),20,31,7,1485,269*,*61.87*,2667,55.68,5,4,2,186,5,2015,2016,1
2,RG Pollock (SA),23,41,4,2256,274,*60.97*,1707+,54.48,7,11,1,246+,11,1963,1970,7
3,GA Headley (WI),22,40,4,2190,270*,*60.83*,416+,56.00,10,5,2,104+,1,1930,1954,24
4,H Sutcliffe (ENG),54,84,9,4555,194,*60.73*,6558+,34.59,16,23,2,202+,6,1924,1935,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,KD Walters (AUS),74,125,14,5357,250,*48.26*,8662+,49.16,15,33,4,525+,23,1965,1981,16
57,GC Smith (ICC/SA),117,205,13,9265,277,*48.25*,15525,59.67,27,38,11,1165,24,2002,2014,12
58,WH Ponsford (AUS),29,48,4,2122,266,*48.22*,3118+,44.77,7,6,1,119+,0,1924,1934,10
59,SJ McCabe (AUS),39,62,5,2748,232,*48.21*,3217+,60.02,6,13,4,241+,5+,1930,1938,8
60,DR Jardine (ENG),22,33,6,1296,127,*48.00*,2110+,25.59,1,10,2,53+,0,1928,1934,6

In [33]:
# split player and the country code

In [36]:
df["Country"] = df["Player"].str.split("(", regex=False).str[1]
df["Player"] = df["Player"].str.split("(").str[0]

In [37]:
df["Country"] = df["Country"].str.replace(")", "", regex=False)

In [94]:
# in case if you fucked up country data, here is the help!
dummy = pd.read_csv("cricketData.csv")
df["Player"] = dummy["Player"]
# df = df.drop(columns=["Country"])

In [38]:
df

,Player,MatchesPlayed,Innings,NotOuts,Runs,HighestScore,AverageScore,BallsFaced,StrikeRate,Centuries,HalfCenturies,0,4s,6s,Start-Date,End-Date,Career-Length,Country
0,DG Bradman,52,80,10,6996,334,*99.94*,9800+,58.60,29,13,7,626+,6,1928,1948,20,AUS
1,AC Voges,20,31,7,1485,269*,*61.87*,2667,55.68,5,4,2,186,5,2015,2016,1,AUS
2,RG Pollock,23,41,4,2256,274,*60.97*,1707+,54.48,7,11,1,246+,11,1963,1970,7,SA
3,GA Headley,22,40,4,2190,270*,*60.83*,416+,56.00,10,5,2,104+,1,1930,1954,24,WI
4,H Sutcliffe,54,84,9,4555,194,*60.73*,6558+,34.59,16,23,2,202+,6,1924,1935,11,ENG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,KD Walters,74,125,14,5357,250,*48.26*,8662+,49.16,15,33,4,525+,23,1965,1981,16,AUS
57,GC Smith,117,205,13,9265,277,*48.25*,15525,59.67,27,38,11,1165,24,2002,2014,12,ICC/SA
58,WH Ponsford,29,48,4,2122,266,*48.22*,3118+,44.77,7,6,1,119+,0,1924,1934,10,AUS
59,SJ McCabe,39,62,5,2748,232,*48.21*,3217+,60.02,6,13,4,241+,5+,1930,1938,8,AUS
60,DR Jardine,22,33,6,1296,127,*48.00*,2110+,25.59,1,10,2,53+,0,1928,1934,6,ENG

In [2]:
# fix up data type of columns

In [43]:
df['MatchesPlayed'].dtypes # this would likely give you a string

dtype('O')

In [51]:
# clean the MatchesPlayed Column. It contains * somewhere
df['MatchesPlayed'] = df['MatchesPlayed'].str.replace("*", '')
df['MatchesPlayed'] = np.int64(df['MatchesPlayed'])
df['MatchesPlayed'].dtypes

dtype('int64')

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 60
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         61 non-null     object
 1   MatchesPlayed  61 non-null     int64
 2   Innings        61 non-null     int64
 3   NotOuts        61 non-null     int64
 4   Runs           61 non-null     int64
 5   HighestScore   61 non-null     object
 6   AverageScore   61 non-null     object
 7   BallsFaced     61 non-null     object
 8   StrikeRate     61 non-null     float64
 9   Centuries      61 non-null     int64
 10  HalfCenturies  61 non-null     int64
 11  0              61 non-null     int64
 12  4s             61 non-null     object
 13  6s             61 non-null     object
 14  Start-Date     61 non-null     object
 15  End-Date       61 non-null     object
 16  Career-Length  61 non-null     int64
 17  Country        61 non-null     object
dtypes: float64(1), int64(8), object(9)
memory usage: 9.1+ KB

In [53]:
# clean the HighestScore Column. It contains * somewhere
df['HighestScore'] = df['HighestScore'].str.replace("*", '')
df['HighestScore'] = np.int64(df['HighestScore'])
df['HighestScore'].dtypes

dtype('int64')

In [55]:
# clean the AverageScore Column. It contains * somewhere
df['AverageScore'] = df['AverageScore'].str.replace("*", '')
df['AverageScore'] = np.float64(df['AverageScore'])
df['AverageScore'].dtypes

dtype('float64')

In [57]:
# clean the BallsFaced Column. It contains * somewhere
df['BallsFaced'] = df['BallsFaced'].str.replace("+", '')
df['BallsFaced'] = np.float64(df['BallsFaced'])
df['BallsFaced'].dtypes

dtype('float64')

In [61]:
df.loc[:, ['4s', '6s']] = df.loc[:, ['4s', '6s']].apply(lambda x: x.str.replace("+", ''))

In [74]:
#convert into an integer
df['4s'] = np.int64(df['4s'])
df['6s'] = np.int64(df['6s'])

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 60
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         61 non-null     object
 1   MatchesPlayed  61 non-null     int64
 2   Innings        61 non-null     int64
 3   NotOuts        61 non-null     int64
 4   Runs           61 non-null     int64
 5   HighestScore   61 non-null     int64
 6   AverageScore   61 non-null     float64
 7   BallsFaced     58 non-null     float64
 8   StrikeRate     61 non-null     float64
 9   Centuries      61 non-null     int64
 10  HalfCenturies  61 non-null     int64
 11  0              61 non-null     int64
 12  4s             61 non-null     int64
 13  6s             61 non-null     int64
 14  Start-Date     61 non-null     object
 15  End-Date       61 non-null     object
 16  Career-Length  61 non-null     int64
 17  Country        61 non-null     object
dtypes: float64(3), int64(11), object(4)
memory usage: 9.1+ KB

In [92]:
df['Start-Date']  = pd.to_datetime(df['Start-Date'])
df['End-Date']  = pd.to_datetime(df['End-Date'])

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61 entries, 0 to 60
Data columns (total 18 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Player         61 non-null     object
 1   MatchesPlayed  61 non-null     int64
 2   Innings        61 non-null     int64
 3   NotOuts        61 non-null     int64
 4   Runs           61 non-null     int64
 5   HighestScore   61 non-null     int64
 6   AverageScore   61 non-null     float64
 7   BallsFaced     58 non-null     float64
 8   StrikeRate     61 non-null     float64
 9   Centuries      61 non-null     int64
 10  HalfCenturies  61 non-null     int64
 11  0              61 non-null     int64
 12  4s             61 non-null     int64
 13  6s             61 non-null     int64
 14  Start-Date     61 non-null     datetime64[ns]
 15  End-Date       61 non-null     datetime64[ns]
 16  Career-Length  61 non-null     int64
 17  Country        61 non-null     object
dtypes: datetime64[ns](2), float64(3), int64(11), object(2)
memory usage: 9.1+ KB

In [87]:
# Questions-

In [89]:
# 1. drop the row for person named RG Pollock

In [102]:
df = df.drop(df[df['Player'] == 'KD Walters'].index, axis=0)

In [105]:
# or directly delete with his index number:
# df = df.drop(index, axis=0)
# df = df.drop(index=<index>)

In [119]:
df.head()

,Player,MatchesPlayed,Innings,NotOuts,Runs,HighestScore,AverageScore,BallsFaced,StrikeRate,Centuries,HalfCenturies,0,4s,6s,Start-Date,End-Date,Career-Length,Country
0,DG Bradman,52,80,10,6996,334,99.94,9800.0,58.60,29,13,7,626,6,1928-01-01,1948-01-01,20,AUS
1,AC Voges,20,31,7,1485,269,61.87,2667.0,55.68,5,4,2,186,5,2015-01-01,2016-01-01,1,AUS
3,GA Headley,22,40,4,2190,270,60.83,416.0,56.00,10,5,2,104,1,1930-01-01,1954-01-01,24,WI
4,H Sutcliffe,54,84,9,4555,194,60.73,6558.0,34.59,16,23,2,202,6,1924-01-01,1935-01-01,11,ENG
5,E Paynter,20,31,5,1540,243,59.23,1288.0,45.88,4,7,3,125,4,1931-01-01,1939-01-01,8,ENG

In [117]:
# 2. Average Batting Strike Rate for cricketers who played over 10 year

In [123]:
ExperiencedPlayers = df[df['Career-Length']>10]
avgStrikeRate = ExperiencedPlayers['StrikeRate'].mean()
avgStrikeRate

np.float64(49.68127906976744)

In [124]:
# 3. Find number of cricketers who player before 1960

In [129]:
oldPlayers = df['End-Date'].apply(lambda x: x.year < 1960)

In [131]:
oldPlayers

0      True
1     False
3      True
4      True
5      True
6     False
7      True
8     False
9      True
10    False
11    False
12     True
13    False
14     True
15    False
16    False
17     True
18    False
19    False
20    False
21    False
22     True
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31     True
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43     True
44    False
45    False
46    False
47     True
48    False
49    False
50    False
51    False
52     True
53     True
54    False
55    False
56    False
57    False
58     True
59     True
60     True
Name: End-Date, dtype: bool